Added db seeding
team-jasmijn/backend pull request #10
Opened 2022-12-01 11:07 UTC by SilGosker

Added Seed class and method, added Arjan as admin to the DB and some profile settings

2022-12-01 12:47 UTC, marnixah requested changes

2022-12-01 12:47 UTC, marnixah commented on Data/Migrations/20221201110602_initial seed.cs
> +                values: new object[] { 1, "artimmerman@landstede.nl", "$2a$11$A1PAL2tcek6yMqg8VVVzauteuOFGnD1S4DoqlPP/Hf9ulBwfJTS8y", null, "Arjan Timmerman", "$2a$11$FIhli04K3CDnTp4ObcYIb.", "Africa
Maybe add a comment with the original unhashed password?

2022-12-01 12:47 UTC, marnixah commented on Data/Migrations/ContextModelSnapshot.cs
> +                            Hash = "$2a$11$A1PAL2tcek6yMqg8VVVzauteuOFGnD1S4DoqlPP/Hf9ulBwfJTS8y",
Same here

2022-12-01 12:47 UTC, marnixah commented on Data/Migrations/SeedConfiguration.cs
> +                Salt = "$2a$11$FIhli04K3CDnTp4ObcYIb.", //testen as password
"testen" is the password? If so, why is the comment on the salt?

2022-12-01 13:55 UTC, HUSKUT commented on Data/Migrations/SeedConfiguration.cs
> +                Salt = "$2a$11$FIhli04K3CDnTp4ObcYIb.", //testen as password
very salty comment

2022-12-05 08:54 UTC, SilGosker commented on Data/Migrations/SeedConfiguration.cs
> +                Salt = "$2a$11$FIhli04K3CDnTp4ObcYIb.", //testen as password
You're right, fixed it

2022-12-05 08:55 UTC, marnixah approved these changes

2022-12-05 08:55 UTC, HUSKUT approved these changes

2022-12-05 08:55 UTC, HUSKUT commented
LGTM

2022-12-05 08:56 UTC, merged